trool/config/routes.rb
Trool::Application.routes.draw do
  resources :pos do
    resources :messages
  end

  resources :pots

  get "welcome/index"

  match 'pos/:id/download' => 'pos#download', :as => :download_po

  root :to => "pots#index"

end

trool/app/models/pot.rb
require 'date'
require 'message'

class Pot < ActiveRecord::Base
  has_many :pos, :dependent => :destroy

  # User uploads a new pot file
  # TODO marking as deprecated
  def update_data(filedata)
    parser = PotInputParser.new filedata
    data = parser.parse_meta
    data[:filedata] = filedata

    # Update meta information
    self.update_attributes(data)

    # Update all related po files
    self.pos.each do |po|
      oldmsgs = po.messages
      uplmsgs = parser.parse_messages

      # Create messages that are in uplmsgs but not in oldmsgs
      oldids = oldmsgs.map {|msg| msg.msgid}
      uplmsgs.each do |msg|
        if not oldids.include? msg.msgid
          # New message - create db entry
          po.messages.push msg
        end
      end

      # Messages to be marked for deletion in next round
      uplids = uplmsgs.map {|msg| msg.msgid}
      oldmsgs.each do |msg|
        if not uplids.include? msg.msgid
          # Message not in uploaded file - mark for removal
          # TODO mark as deprecated
          msg.destroy
        end
      end

      return self.save

      # TODO if a phrase has a msgid which is only slightly
      # different from some msgid in db and msgstr is empty -- copy
      # msgstr and mark as fuzzy
      # e.g. require 'text'; Text::Levenshtein.distance('a', 'a')

      # TODO if a phrase has a different non-empty msgstr
      # in the uploaded file -- mark for merge [OR simply add new
      # version as default when versioning is implemented]
      # NOTE we only need this if we allow uploading PO files (do we?)
    end
  end
end

# Returns hash from which Pot can be populated
# In fact this is a PO, not POT file parser
# POT files are PO files with empty msgstr
class PotInputParser
  attr_reader :all_dict;

  def initialize(content)
    @pot = content
    @all_dict = {}
  end

  # Parse pot information
  # Messages should only be parsed when we create po objects
  def parse_meta
    parse_copyright
    parse_headers
    return @all_dict
  end

  def parse_copyright
    # Fourth line of the content
    raise "Empty @pot, please check if you properly constructed" unless @pot
    line1, line2, line3, line4 = @pot.split("\n").collect { |l| l.chomp }[0..3]
    x, first_author, first_author_email, first_author_year =\
        line4.match(/# (.*) <(.*)>, (\d+)/).to_a
    name = line3.match(/distributed under the same license as the (.*) package./)[1]
    if not (first_author and first_author_email and first_author_year)
      raise "Wrong Line: %s expected author, email, year." % line4
    end
    @all_dict[:title] = line1.sub(/^# /, '')
    @all_dict[:name] = name
    @all_dict[:first_author] = first_author
    @all_dict[:first_author_email] = first_author_email
    @all_dict[:first_author_year] = Integer(first_author_year)
  end

  def parse_headers
    fetchable = {
        :project_id_version => "Project-Id-Version: (.*)\\\\n",
        :report_msgid_bugs_to => "Report-Msgid-Bugs-To: (.*)\\\\n",
        :pot_creation_date => "POT-Creation-Date: (.*)\\\\n",
        :last_translator => "Last-Translator: (.*)\\\\n",
        :language_team => "Language-Team: (.*)\\\\n",
        #:mime_version => "MIME-Version: (.*)\\\\n",
        :content_type => "Content-Type: (.*)\\\\n",
        :content_transfer_encoding => "Content-Transfer-Encoding: (.*)\\\\n",
    }
    fetchable.each { |k,re| 
        val = @pot.match(re)[1]
        raise "Wrong %s: %s" % [k.replace(/: .*/, ''), val] unless val
        @all_dict[k] = val
    }
    @all_dict[:pot_creation_date] = DateTime.parse(
        @all_dict[:pot_creation_date])
  end

  def parse_messages
      re = /(?:\r\n|\n){2,}/
      messages = @pot.split(re)
      raise "messages empty" unless messages

      messages.reject!{ |item| item.blank? }
      messages = messages[1..-1]
      @all_dict[:msg] = []
      raise "messages empty" unless messages
      messages.each do |msg|
        parser = MessageParser.new msg 
        @all_dict[:msg].push parser.msg
      end
      return @all_dict[:msg]
  end
end

trool/app/controllers/pots_controller.rb
require ::Rails.root.to_s+'/app/models/pot.rb'

class PotsController < ApplicationController
  # GET /pots
  # GET /pots.xml
  def index
    @pots = Pot.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pots }
    end
  end

  # GET /pots/1
  # GET /pots/1.xml
  def show
    @pot = Pot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pot }
    end
  end

  # GET /pots/new
  # GET /pots/new.xml
  def new
    @pot = Pot.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pot }
    end
  end

  # GET /pots/1/edit
  def edit
    @pot = Pot.find(params[:id])
  end

  # POST /pots
  # POST /pots.xml
  def create
    # Parse pot file header
    potdata = params[:pot][:filedata]
    parser = PotInputParser.new potdata

    # Form a hash for creating a Pot object
    data = {
      :filedata => potdata,
    }.merge parser.parse_meta
    @pot = Pot.new(data)

    respond_to do |format|
      if @pot.save
        format.html { redirect_to(@pot, :notice => 'Pot was successfully created.') }
        format.xml  { render :xml => @pot, :status => :created, :location => @pot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pots/1
  # PUT /pots/1.xml
  def update
    potdata = params[:pot][:filedata]
    @pot = Pot.find(params[:id])

    respond_to do |format|
      if @pot.update_data potdata
        format.html { redirect_to(@pot, :notice => 'Pot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pots/1
  # DELETE /pots/1.xml
  def destroy
    @pot = Pot.find(params[:id])
    @pot.destroy

    respond_to do |format|
      format.html { redirect_to(pots_url) }
      format.xml  { head :ok }
    end
  end
end

trool/app/helpers/pots_helper.rb
module PotsHelper
end

trool/app/views/pots/_form.html.erb
<%= form_for(@pot) do |f| %>
  <% if @pot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pot.errors.count, "error") %> prohibited this pot from being saved:</h2>

      <ul>
      <% @pot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filedata %><br />
    <%= f.text_area :filedata %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trool/app/views/pots/edit.html.erb
<h1>Editing pot</h1>

<%= render 'form' %>

<%= link_to 'Show', @pot %> |
<%= link_to 'Back', pots_path %>

trool/app/views/pots/index.html.erb
<h1>Projects</h1>

<table>
<% @pots.each do |pot| %>
  <tr>
    <td><%= link_to pot.title, pot %></td>
    <td><%= link_to raw('&#10000;'), edit_pot_path(pot),
            :class => 'plain' %></td>
    <td><%= link_to raw('&#10005;'), pot, :confirm => 'Are you sure?',
            :class => 'plain', :method => :delete %></td>
    <td> | </td>
    <td>
        <% pot.pos.each do |po| %>
            <%= link_to po.lang, po %>
        <% end %>
    </td>
    <td> | </td>
    <td><%= link_to "Translate to your language!", new_po_path %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add project', new_pot_path %>

trool/app/views/pots/new.html.erb
<h1>New pot</h1>

<%= render 'form' %>

<%= link_to 'Back', pots_path %>

trool/app/views/pots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pot.name %>
</p>

<p>
  <b>Lang:</b>
  <%= @pot.lang %>
</p>

<p>
  <b>Title:</b>
  <%= @pot.title %>
</p>

<p>
  <b>Year:</b>
  <%= @pot.year %>
</p>

<p>
  <b>First author:</b>
  <%= @pot.first_author %>
</p>

<p>
  <b>First author email:</b>
  <%= @pot.first_author_email %>
</p>

<p>
  <b>First author year:</b>
  <%= @pot.first_author_year %>
</p>

<p>
  <b>Project id version:</b>
  <%= @pot.project_id_version %>
</p>

<p>
  <b>Report msgid bugs to:</b>
  <%= @pot.report_msgid_bugs_to %>
</p>

<p>
  <b>Pot creation date:</b>
  <%= @pot.pot_creation_date %>
</p>

<p>
  <b>Last translator:</b>
  <%= @pot.last_translator %>
</p>

<p>
  <b>Language team:</b>
  <%= @pot.language_team %>
</p>

<p>
  <b>Language:</b>
  <%= @pot.language %>
</p>

<p>
  <b>Content type:</b>
  <%= @pot.content_type %>
</p>

<p>
  <b>Content transfer encoding:</b>
  <%= @pot.content_transfer_encoding %>
</p>


<%= link_to 'Edit', edit_pot_path(@pot) %> |
<%= link_to 'Back', pots_path %>