trool/config/routes.rb
Trool::Application.routes.draw do
  resources :pos do
    resources :messages
  end

  resources :pots

  get "welcome/index"

  match 'pos/:id/download' => 'pos#download', :as => :download_po

  root :to => "pots#index"

end

trool/app/models/po.rb
require 'ruby-debug'
require 'date'
require Rails.root.to_s + '/app/models/pot'

class Po < ActiveRecord::Base
  belongs_to :pot
  has_many :messages, :dependent => :destroy

  def output
    @po = self
    @pot = self.pot

    ## TODO: fields below
    # TODO: last edit of message?
    po_revision_date = DateTime.now.strftime("%F %T %z")
    pot_creation_date = @pot.pot_creation_date.strftime("%F %T %z")

    ret = %{# #{@pot.title}
# Copyright (C) #{@pot.first_author_year} #{@pot.first_author}
# This file is distributed under the same license as the #{@pot.name} package.
# #{@pot.first_author} <#{@pot.first_author_email}>, #{@pot.first_author_year}.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: #{@pot.project_id_version}"
"Report-Msgid-Bugs-To: #{@pot.report_msgid_bugs_to}"
"POT-Creation-Date: #{pot_creation_date}"
"PO-Revision-Date: #{po_revision_date}"
"Last-Translator: #{@pot.last_translator}"
"Language-Team: #{@pot.language_team}"
"Language: #{@po.lang}"
"MIME-Version: 1.0"
"Content-Type: #{@pot.content_type}"
"Content-Transfer-Encoding: #{@pot.content_transfer_encoding}"

} + messages_string
  end

  # Create messages from PO data file
  def populate_from_po(filedata)
    # Parse the uploaded PO file with msgstrs
    poparser = PotInputParser.new filedata
    poparser.parse_messages

    # Parse the POT template
    potparser = PotInputParser.new self.pot.filedata
    potparser.parse_messages

    # PO and POT files must have the same msgids
    poids = poparser.all_dict[:msg].map {|msg| msg.msgid}
    potids = potparser.all_dict[:msg].map {|msg| msg.msgid}
    unless poids.sort! == potids.sort!
      raise "Messages in PO file are different from messages in POT file!"
    end

    poparser.all_dict[:msg].each {|msg| self.messages.push(msg)}
  end

  # Create empty messages
  def populate_from_pot
    potparser = PotInputParser.new self.pot.filedata
    potparser.parse_messages
    potparser.all_dict[:msg].each {|msg| self.messages.push(msg)}
  end

  # Output a substring of po file containing messages
  def messages_string
    strings = []
    self.messages.each do |msg|
      strings.push msg.to_string
    end
    return strings.join "\n\n"
  end
end

trool/app/controllers/pos_controller.rb
class PosController < ApplicationController
  # GET /pos
  # GET /pos.xml
  def index
    @pos = Po.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pos }
    end
  end

  # GET /pos/1
  def show
    @po = Po.find(params[:id])
    show = request.GET.fetch('show', nil)
    case show
    when 'translated'
      @messages = @po.messages.where("msgstr != ''").where("fuzzy == ?", false)
    when 'untranslated'
      @messages = @po.messages.where("msgstr == '' OR fuzzy == ?", true)
    else
      @messages = @po.messages
    end

    unless request.GET.fetch(:filter, '').blank?
      @messages = @messages.where("msgid LIKE ? OR msgstr LIKE ?",
                      "%#{request.GET[:filter]}%", "%#{request.GET[:filter]}%")
    end

    if request.xhr?
      render :partial => "messages", :messages => @messages
    else
      respond_to do |format|
        format.html # show.html.erb
      end
    end
  end

  def messages
    render :partial => ""
  end

  # GET /pos/new
  # GET /pos/new.xml
  def new
    @po = Po.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @po }
    end
  end

  # GET /pos/1/edit
  def edit
    @po = Po.find(params[:id])
  end

  # POST /pos
  # POST /pos.xml
  def create
    params[:po][:pot] = Pot.find(params[:pot][:id])

    # Create po file
    @po = Po.new(params[:po])
    if params[:data] and not params[:data].empty?
      @po.populate_from_po(params[:data])
    else
      @po.populate_from_pot
    end

    respond_to do |format|
      if @po.save
        format.html { redirect_to(@po, :notice => 'Po was successfully created.') }
        format.xml  { render :xml => @po, :status => :created, :location => @po }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @po.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pos/1
  # PUT /pos/1.xml
  def update
    #params[:po][:pot] = Pot.find(params[:po][:pot])
    @po = Po.find(params[:id])

    respond_to do |format|
      if @po.update_attributes(params[:po])
        format.html { redirect_to(@po, :notice => 'Po was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @po.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pos/1
  # DELETE /pos/1.xml
  def destroy
    @po = Po.find(params[:id])
    @po.destroy

    respond_to do |format|
      format.html { redirect_to(pos_url) }
      format.xml  { head :ok }
    end
  end

  # GET /pos/1/download
  # TODO mo download
  def download
    @po = Po.find(params[:id])
    render :text => @po.output, :content_type => 'text/plain'
  end
end

trool/app/helpers/pos_helper.rb
module PosHelper
end

trool/app/views/pos/_form.html.erb
<%= form_for(@po) do |f| %>
  <% if @po.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@po.errors.count, "error") %> prohibited this po from being saved:</h2>

      <ul>
      <% @po.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lang %><br />
    <%= f.text_field :lang %>
  </div>
  <div class="field">
    <%= f.label :translator %><br />
    <%= f.text_field :translator %>
  </div>
  <div class="field">
    <%= f.label :pot %><br />
    <%= f.text_field :pot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trool/app/views/pos/_messages.erb
<% @messages.each do |msg| %>
<tr>
  <td class="msgid"><%= h(msg.msgid).gsub(/( +)/, '<span>\1</span>').html_safe %></td>
  <td class="msgstr">
    <%= form_for :msg, :url => po_message_url(@po, msg), :remote => true,
        :html => { :method => :put, :class => 'msgstr-form',
                   :autocomplete => :off } do |f| %>
         <%= f.text_area :msgstr, :id => "msgstr-text-#{msg.id}",
                         :class => "msgstr_text",
                         :value => msg.msgstr, :rows => msg.msgid.count("\n") + 1 %>
    <% end %>
    </td>
    <td class="msgstatus"></td>
    <td class="msgstuff">
    <%= form_for :msg, :url => po_message_url(@po, msg),
                 :remote => true, :html => { :method => :put } do |f| %>
       <%= f.check_box :fuzzy, :name => "fuzzy-#{msg.id}", :checked => msg.fuzzy %>
       <%= f.label :fuzzy %>
     <% end %>
  </td>
</tr>
<% end %>

trool/app/views/pos/edit.html.erb
<h1>Editing po</h1>

<%= render 'form' %>

<%= link_to 'Show', @po %> |
<%= link_to 'Back', pos_path %>

trool/app/views/pos/index.html.erb
<h1>Listing pos</h1>

<table>
  <tr>
    <th>Lang</th>
    <th>Translator</th>
    <th>Pot</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pos.each do |po| %>
  <tr>
    <td><%= po.lang %></td>
    <td><%= po.translator %></td>
    <td><%= po.pot %></td>
    <td><%= link_to 'Show', po %></td>
    <td><%= link_to 'Edit', edit_po_path(po) %></td>
    <td><%= link_to 'Destroy', po, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Po', new_po_path %>

trool/app/views/pos/new.html.erb
<h1>New po</h1>

<%= form_for :po, :url => :pos do |f| %>
    <table style="margin-top: 20px">
        <tr> <td>Project:</td><td><%= collection_select :pot, :id, Pot.all, :id, :title  %></td>
        <tr> <td><%= f.label :lang %></td><td><%= f.text_field :lang %></td>
        <tr> <td><%= f.label :translator %></td><td><%= f.text_field :translator %></td>
        <tr> <td colspan="2">
                <a href="#" onclick="$('#data').toggle(); return false">Already have a .po file?</a></td>
        <tr id="data" style="display: none;">
            <td>Po file</td>
            <td><%= text_area_tag :data, nil, :rows=>20, :cols=>40 %></td>
        <tr> <td colspan="2"><input type="submit" value="Add language!" /></td>
    </table>
<% end %>

<%= link_to 'Back', pos_path %>

trool/app/views/pos/show.html.erb
<%= content_for :below_body do %>
<% end %>

<p id="notice"><%= notice %></p>


<h1> <%= @po.pot.title %> &#8594; <%= @po.lang %> </h1>

<div id="navigation_statuses">
  <div class="fleft">
    <ul>
        <li> <%= link_to "All", "?", :remote => true, :class => 'loadmsg',
                 :title => "All messages" %>
        <li> <%= link_to "Untranslated/Unclear", "?show=untranslated", :remote => true,
                 :class => 'loadmsg', :title => "Untranslated messages" %>
        <li><%= link_to "Translated", "?show=translated", :remote => true,
                 :class => 'loadmsg', :title => "Translated messages" %>
        <li><%= text_field_tag :filter, 'Search All', :class => 'filter loadmsg empty',
                 :title => 'Search all', :autocomplete => 'off' %>
    </ul>
  </div>
  <div class="fright"><a href="<%= download_po_url(:id => @po.id) %>">Download PO</a></div>
  
  <div class="cl"></div>
</div>

<table id="messages">
  <%= render :partial => "messages", :messages => @messages %>
</table>

<%= link_to 'Edit', edit_po_path(@po) %> |
<%= link_to 'Back', pos_path %>
<%= javascript_include_tag 'po' %>